In [23]:
import numpy as np
import pandas as pd

In [55]:
traffic_df = pd.read_csv('trafficdata.csv', delimiter = ';')

In [25]:
traffic_df

,index,City,ONS LACode,Area,CP,S Ref E,S Ref N,S_Ref_Latitude,S_Ref_Longitude,Road,...,LGV,HGVR2,HGVR3,HGVR4,HGVA3,HGVA5,HGVA6,HGV,AMV,hours
0,0,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,7.0,0
1,1,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,11.0,1
2,2,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,1,1.0,0.0,0.0,0,0,0,1.0,7.0,2
3,3,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,9.0,3
4,4,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,1,0.0,0.0,0.0,0,0,0,0.0,12.0,4
5,5,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,1,0.0,0.0,0.0,0,0,0,0.0,13.0,5
6,6,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,14.0,6
7,7,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,1.0,0.0,0.0,0,0,0,1.0,14.0,7
8,8,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,4,0.0,0.0,0.0,0,0,0,0.0,12.0,8
9,9,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,16.0,9
10,10,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,19.0,10
11,11,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,1,0.0,0.0,0.0,0,0,0,0.0,17.0,11
12,12,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,0,0.0,0.0,0.0,0,0,0,0.0,5.0,12
13,13,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,1,0.0,0.0,0.0,0,0,0,0.0,9.0,13
14,14,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,1.0,0.0,0.0,0,0,0,1.0,9.0,14
15,15,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,0,0.0,0.0,0.0,0,0,0,0.0,3.0,15
16,16,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,3,0.0,0.0,0.0,0,0,0,0.0,9.0,16
17,17,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,1,0.0,0.0,0.0,0,0,0,0.0,15.0,17
18,18,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,3,0.0,0.0,0.0,0,0,0,0.0,17.0,18
19,19,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,0,0.0,0.0,0.0,0,0,0,0.0,12.0,19
20,20,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,16.0,20
21,21,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,0,0.0,0.0,0.0,0,0,0,0.0,9.0,21
22,22,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,21.0,22
23,23,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,1,0.0,0.0,0.0,0,0,0,0.0,17.0,23
24,24,East Midlands,E10000024,Nottinghamshire,910005,451147,336827,52.926427,-1.240623,C159,...,45,1.0,0.0,0.0,1,0,0,2.0,404.0,0
25,25,East Midlands,E10000024,Nottinghamshire,910005,451147,336827,52.926427,-1.240623,C159,...,35,2.0,1.0,2.0,0,0,0,5.0,551.0,1
26,26,East Midlands,E10000024,Nottinghamshire,910005,451147,336827,52.926427,-1.240623,C159,...,28,7.0,0.0,0.0,0,0,0,7.0,282.0,2
27,27,East Midlands,E10000024,Nottinghamshire,910005,451147,336827,52.926427,-1.240623,C159,...,30,6.0,0.0,0.0,0,0,0,6.0,235.0,3
28,28,East Midlands,E10000024,Nottinghamshire,910005,451147,336827,52.926427,-1.240623,C159,...,24,2.0,0.0,0.0,0,0,0,2.0,217.0,4
29,29,East Midlands,E10000024,Nottinghamshire,910005,451147,336827,52.926427,-1.240623,C159,...,31,4.0,1.0,0.0,0,0,0,5.0,284.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1743030,1743030,Scotland,S12000033,Aberdeen City,996715,390170,803893,57.125858,-2.163995,U,...,13,1.0,0.0,0.0,0,0,0,1.0,130.0,6
1743031,1743031,Scotland,S12000033,Aberdeen City,996715,390170,803893,57.125858,-2.163995,U,...,13,1.0,0.0,0.0,0,0,0,1.0,135.0,7
1743032,1743032,Scotland,S12000033,Aberdeen City,996715,390170,803893,57.125858,-2.163995,U,...,6,0.0,0.0,0.0,0,0,0,0.0,148.0,8
1743033,1743033,Scotland,S12000033,Aberdeen City,996715,390170,803893,57.125858,-2.163995,U,...,5,0.0,0.0,0.0,0,0,0,0.0,225.0,9
1743034,1743034,Scotland,S12000033,Aberdeen City,996715,390170,803893,57.125858,-2.163995,U,...,8,0.0,0.0,0.0,0,0,0,0.0,293.0,10
1743035,1743035,Scotland,S12000033,Aberdeen City,996715,390170,803893,57.125858,-2.163995,U,...,4,0.0,0.0,0.0,0,0,0,0.0,191.0,11
1743036,1743036,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,15,3.0,0.0,0.0,0,0,0,3.0,82.0,12
1743037,1743037,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,21,0.0,1.0,0.0,0,0,0,1.0,103.0,13
1743038,1743038,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,20,2.0,1.0,0.0,0,0,0,3.0,71.0,14
1743039,1743039,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,22,3.0,2.0,0.0,0,0,0,5.0,73.0,15
1743040,1743040,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,20,2.0,0.0,0.0,0,0,0,2.0,79.0,16
1743041,1743041,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,34,1.0,0.0,0.0,0,0,0,1.0,109.0,17
1743042,1743042,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,18,1.0,1.0,0.0,0,1,0,3.0,94.0,18
1743043,1743043,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,32,2.0,0.0,0.0,0,0,0,2.0,96.0,19
1743044,1743044,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,14,3.0,0.0,0.0,0,0,0,3.0,62.0,20
1743045,1743045,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,15,0.0,0.0,0.0,0,0,0,0.0,79.0,21
1743046,1743046,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,10,2.0,0.0,0.0,0,0,0,2.0,102.0,22
1743047,1743047,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,9,0.0,0.0,0.0,0,0,0,0.0,73.0,23
1743048,1743048,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,31,3.0,1.0,0.0,0,14,5,23.0,151.0,0
1743049,1743049,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,57,8.0,2.0,0.0,1,3,1,15.0,166.0,1
1743050,1743050,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,50,9.0,1.0,0.0,0,7,3,20.0,164.0,2
1743051,1743051,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,47,9.0,3.0,0.0,0,6,3,21.0,188.0,3
1743052,1743052,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,47,6.0,1.0,2.0,0,2,2,13.0,231.0,4
1743053,1743053,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,49,8.0,0.0,0.0,0,6,3,17.0,273.0,5
1743054,1743054,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,55,0.0,4.0,1.0,0,4,2,11.0,255.0,6
1743055,1743055,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,48,4.0,0.0,1.0,0,0,4,9.0,239.0,7
1743056,1743056,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,52,4.0,1.0,0.0,0,5,0,10.0,269.0,8
1743057,1743057,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,43,4.0,1.0,0.0,0,5,0,10.0,319.0,9
1743058,1743058,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,21,1.0,0.0,0.0,0,5,0,6.0,277.0,10
1743059,1743059,Scotland,S12000033,Aberdeen City,996768,394735,806176,57.146442,-2.088645,C,...,22,0.0,0.0,0.0,0,0,0,0.0,168.0,11

In [26]:
traffic_df.count()

index              1743060
City               1743060
ONS LACode         1743060
Area               1743060
CP                 1743060
S Ref E            1743060
S Ref N            1743060
S_Ref_Latitude     1743060
S_Ref_Longitude    1743060
Road               1743060
Road_Name          1571774
CP Location         718714
RCat               1743060
iDir               1743060
Year               1743060
dCount             1743060
PC                 1743060
2WMV               1743060
CAR                1743060
BUS                1743060
LGV                1743060
HGVR2              1743060
HGVR3              1743060
HGVR4              1743060
HGVA3              1743060
HGVA5              1743060
HGVA6              1743060
HGV                1743060
AMV                1743060
hours              1743060
dtype: int64

In [27]:
traffic_df.groupby('City').sum()

,index,CP,S Ref E,S Ref N,S_Ref_Latitude,S_Ref_Longitude,Year,PC,2WMV,CAR,...,LGV,HGVR2,HGVR3,HGVR4,HGVA3,HGVA5,HGVA6,HGV,AMV,hours
City,,,,,,,,,,,,,,,,,,,,,
East Midlands,111952466310,126532022016,62098908780,43823788608,7.055093e+06,-138072.409689,268129692,219973,156972,14651144,...,2122713,286484.0,45294.0,42770.0,31311,40933,35734,482526.0,17688353.0,1535094
East of England,181232293512,198154521096,117785901168,51285959808,1.087253e+07,82934.675829,419313828,409194,240522,22399025,...,3423789,482292.0,62766.0,60148.0,44030,53864,45489,748589.0,27161462.0,2400624
London,102748286496,112684981848,62713851744,21207538872,6.097928e+06,-15910.730442,237857352,597811,470432,18872351,...,3106990,490958.0,54080.0,59656.0,12541,15818,17818,650871.0,23643317.0,1361376
Merseyside,28689845778,31160322720,11127970764,12903209124,1.756017e+06,-96171.542693,66022680,49469,31507,4597841,...,606710,83370.0,12653.0,10697.0,5334,13464,12734,138252.0,5485525.0,378210
North East,73374038153,81349523775,36842405522,46969676892,4.691578e+06,-130539.475104,171849022,112908,70992,10285751,...,1410838,160672.0,25126.0,19194.0,8340,11672,11515,236519.0,12294472.0,983969
North West,129143437872,144989319924,55864200828,63586085604,8.191829e+06,-384866.136141,306709524,262970,154211,19477680,...,2552886,364940.0,50947.0,43611.0,27641,34906,27642,549685.0,23109855.0,1756800
Scotland,94995890914,102074962188,31817415748,75835753328,5.999747e+06,-387554.037954,214134004,93688,65465,12162659,...,1614085,324018.0,49992.0,38475.0,30434,26448,25960,495327.0,14666823.0,1225570
South East,259754894261,278171964327,147358250096,44199596964,1.500181e+07,-152469.619059,588029757,585802,366375,34113173,...,4871400,580881.0,87614.0,78204.0,34960,45091,36139,862889.0,40663273.0,3366821
South West,146466541068,166094392380,58940361400,23049508860,8.909401e+06,-502432.273735,350266924,297614,272655,19612266,...,2971996,346609.0,63312.0,42918.0,29495,38061,35354,555749.0,23728426.0,2005620
Wales,101344563574,104373350750,32414986646,25489840010,5.702155e+06,-386592.641504,220375362,87780,85859,9817254,...,1376605,153092.0,29153.0,17580.0,12561,11688,10265,234339.0,11741191.0,1261222
West Midlands,159591190077,170903057361,71876308695,52105776354,9.433262e+06,-359412.603129,360860796,227246,200419,23420508,...,3168352,388569.0,77318.0,64856.0,35168,58102,54083,678096.0,27946479.0,2065749
Yorkshire & the Humber,129834762255,141023341989,66478846914,63627681957,7.963632e+06,-186932.643760,297528957,269670,164742,16111926,...,2363016,283370.0,48940.0,46578.0,26046,37003,31845,473782.0,19452134.0,1704063

In [28]:
traffic_df.groupby('City').count()

,index,ONS LACode,Area,CP,S Ref E,S Ref N,S_Ref_Latitude,S_Ref_Longitude,Road,Road_Name,...,LGV,HGVR2,HGVR3,HGVR4,HGVA3,HGVA5,HGVA6,HGV,AMV,hours
City,,,,,,,,,,,,,,,,,,,,,
East Midlands,133500,133500,133500,133500,133500,133500,133500,133500,133500,126024,...,133500,133500,133500,133500,133500,133500,133500,133500,133500,133500
East of England,208752,208752,208752,208752,208752,208752,208752,208752,208752,189948,...,208752,208752,208752,208752,208752,208752,208752,208752,208752,208752
London,118416,118416,118416,118416,118416,118416,118416,118416,118416,117696,...,118416,118416,118416,118416,118416,118416,118416,118416,118416,118416
Merseyside,32868,32868,32868,32868,32868,32868,32868,32868,32868,32328,...,32868,32868,32868,32868,32868,32868,32868,32868,32868,32868
North East,85559,85559,85559,85559,85559,85559,85559,85559,85559,75707,...,85559,85559,85559,85559,85559,85559,85559,85559,85559,85559
North West,152712,152712,152712,152712,152712,152712,152712,152712,152712,146400,...,152712,152712,152712,152712,152712,152712,152712,152712,152712,152712
Scotland,106604,106604,106604,106604,106604,106604,106604,106604,106604,82184,...,106604,106604,106604,106604,106604,106604,106604,106604,106604,106604
South East,292739,292739,292739,292739,292739,292739,292739,292739,292739,275807,...,292739,292739,292739,292739,292739,292739,292739,292739,292739,292739
South West,174416,174416,174416,174416,174416,174416,174416,174416,174416,134456,...,174416,174416,174416,174416,174416,174416,174416,174416,174416,174416
Wales,109702,109702,109702,109702,109702,109702,109702,109702,109702,91512,...,109702,109702,109702,109702,109702,109702,109702,109702,109702,109702
West Midlands,179655,179655,179655,179655,179655,179655,179655,179655,179655,164547,...,179655,179655,179655,179655,179655,179655,179655,179655,179655,179655
Yorkshire & the Humber,148137,148137,148137,148137,148137,148137,148137,148137,148137,135165,...,148137,148137,148137,148137,148137,148137,148137,148137,148137,148137

In [29]:
traffic_df.groupby('Area').count()

,index,City,ONS LACode,CP,S Ref E,S Ref N,S_Ref_Latitude,S_Ref_Longitude,Road,Road_Name,...,LGV,HGVR2,HGVR3,HGVR4,HGVA3,HGVA5,HGVA6,HGV,AMV,hours
Area,,,,,,,,,,,,,,,,,,,,,
Aberdeen City,3924,3924,3924,3924,3924,3924,3924,3924,3924,3588,...,3924,3924,3924,3924,3924,3924,3924,3924,3924,3924
Aberdeenshire,8040,8040,8040,8040,8040,8040,8040,8040,8040,4872,...,8040,8040,8040,8040,8040,8040,8040,8040,8040,8040
Angus,3144,3144,3144,3144,3144,3144,3144,3144,3144,2040,...,3144,3144,3144,3144,3144,3144,3144,3144,3144,3144
Argyll & Bute,2256,2256,2256,2256,2256,2256,2256,2256,2256,396,...,2256,2256,2256,2256,2256,2256,2256,2256,2256,2256
Barking and Dagenham,2160,2160,2160,2160,2160,2160,2160,2160,2160,2160,...,2160,2160,2160,2160,2160,2160,2160,2160,2160,2160
Barnet,4200,4200,4200,4200,4200,4200,4200,4200,4200,4200,...,4200,4200,4200,4200,4200,4200,4200,4200,4200,4200
Barnsley,5952,5952,5952,5952,5952,5952,5952,5952,5952,5808,...,5952,5952,5952,5952,5952,5952,5952,5952,5952,5952
Bath and North East Somerset,4836,4836,4836,4836,4836,4836,4836,4836,4836,4836,...,4836,4836,4836,4836,4836,4836,4836,4836,4836,4836
Bedford,4776,4776,4776,4776,4776,4776,4776,4776,4776,4536,...,4776,4776,4776,4776,4776,4776,4776,4776,4776,4776
Bexley,2988,2988,2988,2988,2988,2988,2988,2988,2988,2988,...,2988,2988,2988,2988,2988,2988,2988,2988,2988,2988
Birmingham,32076,32076,32076,32076,32076,32076,32076,32076,32076,32076,...,32076,32076,32076,32076,32076,32076,32076,32076,32076,32076
Blackburn with Darwen,3048,3048,3048,3048,3048,3048,3048,3048,3048,3048,...,3048,3048,3048,3048,3048,3048,3048,3048,3048,3048
Blackpool,3756,3756,3756,3756,3756,3756,3756,3756,3756,3756,...,3756,3756,3756,3756,3756,3756,3756,3756,3756,3756
Blaenau Gwent,2184,2184,2184,2184,2184,2184,2184,2184,2184,1752,...,2184,2184,2184,2184,2184,2184,2184,2184,2184,2184
Bolton,8628,8628,8628,8628,8628,8628,8628,8628,8628,8604,...,8628,8628,8628,8628,8628,8628,8628,8628,8628,8628
Bournemouth,4860,4860,4860,4860,4860,4860,4860,4860,4860,4860,...,4860,4860,4860,4860,4860,4860,4860,4860,4860,4860
Bracknell Forest,3744,3744,3744,3744,3744,3744,3744,3744,3744,3744,...,3744,3744,3744,3744,3744,3744,3744,3744,3744,3744
Bradford,11913,11913,11913,11913,11913,11913,11913,11913,11913,11793,...,11913,11913,11913,11913,11913,11913,11913,11913,11913,11913
Brent,3972,3972,3972,3972,3972,3972,3972,3972,3972,3780,...,3972,3972,3972,3972,3972,3972,3972,3972,3972,3972
Bridgend,4440,4440,4440,4440,4440,4440,4440,4440,4440,4128,...,4440,4440,4440,4440,4440,4440,4440,4440,4440,4440
Brighton and Hove,7536,7536,7536,7536,7536,7536,7536,7536,7536,7536,...,7536,7536,7536,7536,7536,7536,7536,7536,7536,7536
"Bristol, City of",12144,12144,12144,12144,12144,12144,12144,12144,12144,12144,...,12144,12144,12144,12144,12144,12144,12144,12144,12144,12144
Bromley,6840,6840,6840,6840,6840,6840,6840,6840,6840,6840,...,6840,6840,6840,6840,6840,6840,6840,6840,6840,6840
Buckinghamshire,18168,18168,18168,18168,18168,18168,18168,18168,18168,17304,...,18168,18168,18168,18168,18168,18168,18168,18168,18168,18168
Bury,4632,4632,4632,4632,4632,4632,4632,4632,4632,4632,...,4632,4632,4632,4632,4632,4632,4632,4632,4632,4632
Caerphilly,6648,6648,6648,6648,6648,6648,6648,6648,6648,6024,...,6648,6648,6648,6648,6648,6648,6648,6648,6648,6648
Calderdale,4992,4992,4992,4992,4992,4992,4992,4992,4992,4992,...,4992,4992,4992,4992,4992,4992,4992,4992,4992,4992
Cambridgeshire,22524,22524,22524,22524,22524,22524,22524,22524,22524,20172,...,22524,22524,22524,22524,22524,22524,22524,22524,22524,22524
Camden,2484,2484,2484,2484,2484,2484,2484,2484,2484,2484,...,2484,2484,2484,2484,2484,2484,2484,2484,2484,2484
Cardiff,14664,14664,14664,14664,14664,14664,14664,14664,14664,14640,...,14664,14664,14664,14664,14664,14664,14664,14664,14664,14664
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Swindon,7440,7440,7440,7440,7440,7440,7440,7440,7440,7056,...,7440,7440,7440,7440,7440,7440,7440,7440,7440,7440
Tameside,4128,4128,4128,4128,4128,4128,4128,4128,4128,4056,...,4128,4128,4128,4128,4128,4128,4128,4128,4128,4128
Telford and Wrekin,7752,7752,7752,7752,7752,7752,7752,7752,7752,7032,...,7752,7752,7752,7752,7752,7752,7752,7752,7752,7752
The Vale of Glamorgan,5688,5688,5688,5688,5688,5688,5688,5688,5688,5208,...,5688,5688,5688,5688,5688,5688,5688,5688,5688,5688
Thurrock,5148,5148,5148,5148,5148,5148,5148,5148,5148,4812,...,5148,5148,5148,5148,5148,5148,5148,5148,5148,5148
Torbay,3408,3408,3408,3408,3408,3408,3408,3408,3408,3384,...,3408,3408,3408,3408,3408,3408,3408,3408,3408,3408
Torfaen,3936,3936,3936,3936,3936,3936,3936,3936,3936,3792,...,3936,3936,3936,3936,3936,3936,3936,3936,3936,3936
Tower Hamlets,3720,3720,3720,3720,3720,3720,3720,3720,3720,3672,...,3720,3720,3720,3720,3720,3720,3720,3720,3720,3720
Trafford,7536,7536,7536,7536,7536,7536,7536,7536,7536,7536,...,7536,7536,7536,7536,7536,7536,7536,7536,7536,7536
Wakefield,7968,7968,7968,7968,7968,7968,7968,7968,7968,7968,...,7968,7968,7968,7968,7968,7968,7968,7968,7968,7968
Walsall,6060,6060,6060,6060,6060,6060,6060,6060,6060,6012,...,6060,6060,6060,6060,6060,6060,6060,6060,6060,6060
Waltham Forest,1860,1860,1860,1860,1860,1860,1860,1860,1860,1860,...,1860,1860,1860,1860,1860,1860,1860,1860,1860,1860
Wandsworth,3816,3816,3816,3816,3816,3816,3816,3816,3816,3816,...,3816,3816,3816,3816,3816,3816,3816,3816,3816,3816
Warrington,6240,6240,6240,6240,6240,6240,6240,6240,6240,6240,...,6240,6240,6240,6240,6240,6240,6240,6240,6240,6240
Warwickshire,23715,23715,23715,23715,23715,23715,23715,23715,23715,21891,...,23715,23715,23715,23715,23715,23715,23715,23715,23715,23715
West Berkshire,5820,5820,5820,5820,5820,5820,5820,5820,5820,4716,...,5820,5820,5820,5820,5820,5820,5820,5820,5820,5820
West Cheshire,8160,8160,8160,8160,8160,8160,8160,8160,8160,7896,...,8160,8160,8160,8160,8160,8160,8160,8160,8160,8160
West Dunbartonshire,1344,1344,1344,1344,1344,1344,1344,1344,1344,1344,...,1344,1344,1344,1344,1344,1344,1344,1344,1344,1344
West Lothian,3000,3000,3000,3000,3000,3000,3000,3000,3000,2304,...,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
West Sussex,29532,29532,29532,29532,29532,29532,29532,29532,29532,27324,...,29532,29532,29532,29532,29532,29532,29532,29532,29532,29532
Westminster,3072,3072,3072,3072,3072,3072,3072,3072,3072,3072,...,3072,3072,3072,3072,3072,3072,3072,3072,3072,3072
Wigan,7056,7056,7056,7056,7056,7056,7056,7056,7056,7056,...,7056,7056,7056,7056,7056,7056,7056,7056,7056,7056
Wiltshire,15804,15804,15804,15804,15804,15804,15804,15804,15804,11988,...,15804,15804,15804,15804,15804,15804,15804,15804,15804,15804
Windsor and Maidenhead,5016,5016,5016,5016,5016,5016,5016,5016,5016,4752,...,5016,5016,5016,5016,5016,5016,5016,5016,5016,5016
Wirral,7320,7320,7320,7320,7320,7320,7320,7320,7320,7212,...,7320,7320,7320,7320,7320,7320,7320,7320,7320,7320
Wokingham,5064,5064,5064,5064,5064,5064,5064,5064,5064,4896,...,5064,5064,5064,5064,5064,5064,5064,5064,5064,5064
Wolverhampton,6672,6672,6672,6672,6672,6672,6672,6672,6672,6672,...,6672,6672,6672,6672,6672,6672,6672,6672,6672,6672
Worcestershire,19776,19776,19776,19776,19776,19776,19776,19776,19776,18024,...,19776,19776,19776,19776,19776,19776,19776,19776,19776,19776
Wrexham,4188,4188,4188,4188,4188,4188,4188,4188,4188,3948,...,4188,4188,4188,4188,4188,4188,4188,4188,4188,4188
York,5280,5280,5280,5280,5280,5280,5280,5280,5280,5040,...,5280,5280,5280,5280,5280,5280,5280,5280,5280,5280

In [30]:
traffic_df[traffic_df.City == 'Merseyside'][['Area','Year','dCount','Road_Name','hours']]

              Area  Year      dCount       Road_Name  hours
0         Knowsley  2000  2000-06-08  Dunmail Avenue      0
1         Knowsley  2000  2000-06-08  Dunmail Avenue      1
2         Knowsley  2000  2000-06-08  Dunmail Avenue      2
3         Knowsley  2000  2000-06-08  Dunmail Avenue      3
4         Knowsley  2000  2000-06-08  Dunmail Avenue      4
5         Knowsley  2000  2000-06-08  Dunmail Avenue      5
6         Knowsley  2000  2000-06-08  Dunmail Avenue      6
7         Knowsley  2000  2000-06-08  Dunmail Avenue      7
8         Knowsley  2000  2000-06-08  Dunmail Avenue      8
9         Knowsley  2000  2000-06-08  Dunmail Avenue      9
10        Knowsley  2000  2000-06-08  Dunmail Avenue     10
11        Knowsley  2000  2000-06-08  Dunmail Avenue     11
12        Knowsley  2000  2000-06-08  Dunmail Avenue     12
13        Knowsley  2000  2000-06-08  Dunmail Avenue     13
14        Knowsley  2000  2000-06-08  Dunmail Avenue     14
15        Knowsley  2000  2000-06-08  Dunmail Avenue     15
16        Knowsley  2000  2000-06-08  Dunmail Avenue     16
17        Knowsley  2000  2000-06-08  Dunmail Avenue     17
18        Knowsley  2000  2000-06-08  Dunmail Avenue     18
19        Knowsley  2000  2000-06-08  Dunmail Avenue     19
20        Knowsley  2000  2000-06-08  Dunmail Avenue     20
21        Knowsley  2000  2000-06-08  Dunmail Avenue     21
22        Knowsley  2000  2000-06-08  Dunmail Avenue     22
23        Knowsley  2000  2000-06-08  Dunmail Avenue     23
2640        Sefton  2000  2000-05-15    Birkdale Cop      0
2641        Sefton  2000  2000-05-15    Birkdale Cop      1
2642        Sefton  2000  2000-05-15    Birkdale Cop      2
2643        Sefton  2000  2000-05-15    Birkdale Cop      3
2644        Sefton  2000  2000-05-15    Birkdale Cop      4
2645        Sefton  2000  2000-05-15    Birkdale Cop      5
...            ...   ...         ...             ...    ...
1739118  Liverpool  2016  2016-09-29  DEYSBROOK LANE      6
1739119  Liverpool  2016  2016-09-29  DEYSBROOK LANE      7
1739120  Liverpool  2016  2016-09-29  DEYSBROOK LANE      8
1739121  Liverpool  2016  2016-09-29  DEYSBROOK LANE      9
1739122  Liverpool  2016  2016-09-29  DEYSBROOK LANE     10
1739123  Liverpool  2016  2016-09-29  DEYSBROOK LANE     11
1739124  Liverpool  2016  2016-05-05      LOVEL ROAD     12
1739125  Liverpool  2016  2016-05-05      LOVEL ROAD     13
1739126  Liverpool  2016  2016-05-05      LOVEL ROAD     14
1739127  Liverpool  2016  2016-05-05      LOVEL ROAD     15
1739128  Liverpool  2016  2016-05-05      LOVEL ROAD     16
1739129  Liverpool  2016  2016-05-05      LOVEL ROAD     17
1739130  Liverpool  2016  2016-05-05      LOVEL ROAD     18
1739131  Liverpool  2016  2016-05-05      LOVEL ROAD     19
1739132  Liverpool  2016  2016-05-05      LOVEL ROAD     20
1739133  Liverpool  2016  2016-05-05      LOVEL ROAD     21
1739134  Liverpool  2016  2016-05-05      LOVEL ROAD     22
1739135  Liverpool  2016  2016-05-05      LOVEL ROAD     23
1739136  Liverpool  2016  2016-05-05      LOVEL ROAD      0
1739137  Liverpool  2016  2016-05-05      LOVEL ROAD      1
1739138  Liverpool  2016  2016-05-05      LOVEL ROAD      2
1739139  Liverpool  2016  2016-05-05      LOVEL ROAD      3
1739140  Liverpool  2016  2016-05-05      LOVEL ROAD      4
1739141  Liverpool  2016  2016-05-05      LOVEL ROAD      5
1739142  Liverpool  2016  2016-05-05      LOVEL ROAD      6
1739143  Liverpool  2016  2016-05-05      LOVEL ROAD      7
1739144  Liverpool  2016  2016-05-05      LOVEL ROAD      8
1739145  Liverpool  2016  2016-05-05      LOVEL ROAD      9
1739146  Liverpool  2016  2016-05-05      LOVEL ROAD     10
1739147  Liverpool  2016  2016-05-05      LOVEL ROAD     11

[32868 rows x 5 columns]

In [31]:
traffic_df[traffic_df.City == 'Merseyside'].groupby(['Road_Name']).count()[['Area','Year','dCount','CAR','BUS', 'LGV','HGVR2','HGVR3','HGVR4','HGVA3','HGVA5','HGVA6','HGV','AMV','hours']]

,Area,Year,dCount,CAR,BUS,LGV,HGVR2,HGVR3,HGVR4,HGVA3,HGVA5,HGVA6,HGV,AMV,hours
Road_Name,,,,,,,,,,,,,,,
AIGBURTH DRIVE,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
ALDERFIELD DRIVE,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
ALLERTON ROAD,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
ALMA ROAD,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
ALTWAY,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192
ARNSIDE ROAD,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
ATHERTON STREET,144,144,144,144,144,144,144,144,144,144,144,144,144,144,144
Admiral Street,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240
Albany Road,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216
Alder Lane,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240
Arrowe Brook Lane,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240
Ash Grove,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240
BALMORAL AVENUE,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
BEDFORD ROAD,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192
BEECHTREE ROAD,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
BERMUDA ROAD,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
BEVERSBROOK ROAD,144,144,144,144,144,144,144,144,144,144,144,144,144,144,144
BISHOP DRIVE,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192
BLACKBURNE STREET,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
BLENHEIM STREET,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
BLUEFIELDS STREET,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
BOUNDARY ROAD,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192
BREEZE LANE,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
BROADMEAD,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
BROOK HEY DRIVE,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
BROOK VALE,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192
BROWN'S LANE,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
BULFORD ROAD,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192
BYRON CLOSE,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
Baxters Lane,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TITHEBARN ROAD,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
TOWCESTER STREET,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
TRAVERS' ENTRY,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192
TUDOR ROAD,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192
VICTORIA ROAD,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
VIEW ROAD,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
VILLAGE ROAD,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216
Victoria Road,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216
WARD GROVE/HIGHFIELD SOUTH,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
WARGRAVE ROAD,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
WARWICK AVENUE,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
WASHINGTON PARADE,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
WATERPARK DRIVE,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96
WAVERTREE ROAD,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
WAYLANDS DRIVE,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
WELLCROFT ROAD,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
WESTERN AVENUE,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
WESTMINSTER ROAD,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168
WHALEY LANE,144,144,144,144,144,144,144,144,144,144,144,144,144,144,144
WOODEND AVENUE,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
WOODEND LANE,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
WOODWARD ROAD,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192
WOOLTON ROAD,216,216,216,216,216,216,216,216,216,216,216,216,216,216,216
WYCHERLEY STREET,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
Warren Road,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240
Waterland Lane,240,240,240,240,240,240,240,240,240,240,240,240,240,240,240
Wilson Road,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120
Windermere Drive,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
Woolton Road,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192
Worcester Road,168,168,168,168,168,168,168,168,168,168,168,168,168,168,168

In [32]:
traffic_df['AMV'].sum()

247581310.0

In [34]:
traffic_df1 = traffic_df[traffic_df.City == 'Merseyside']
traffic_df2 = traffic_df1[traffic_df1.Area == 'Knowsley']
traffic_df3 = traffic_df2[traffic_df2.dCount == '2000-06-08']
traffic_df4 = traffic_df3[traffic_df3.hours == 1]

car_num = traffic_df4['CAR'].sum()
bus_num = traffic_df4['BUS'].sum()
lgv_num = traffic_df4['LGV'].sum()
h2_num = traffic_df4['HGVR2'].sum()
h3_num = traffic_df4['HGVR3'].sum()
h4_num = traffic_df4['HGVR4'].sum()
v3_num = traffic_df4['HGVA3'].sum()
v5_num = traffic_df4['HGVA5'].sum()
v6_num = traffic_df4['HGVA6'].sum()
hgv_num = traffic_df4['HGV'].sum()
amv_num = traffic_df4['AMV'].sum()

veh_sum = car_num + bus_num + lgv_num + h2_num + h3_num + h4_num + v3_num + v5_num + v6_num + hgv_num + amv_num

veh_sum

22.0

In [56]:
t = traffic_df[traffic_df.Area == 'Knowsley']

In [35]:
traffic_df2

,index,City,ONS LACode,Area,CP,S Ref E,S Ref N,S_Ref_Latitude,S_Ref_Longitude,Road,...,LGV,HGVR2,HGVR3,HGVR4,HGVA3,HGVA5,HGVA6,HGV,AMV,hours
0,0,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,7.0,0
1,1,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,11.0,1
2,2,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,1,1.0,0.0,0.0,0,0,0,1.0,7.0,2
3,3,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,9.0,3
4,4,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,1,0.0,0.0,0.0,0,0,0,0.0,12.0,4
5,5,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,1,0.0,0.0,0.0,0,0,0,0.0,13.0,5
6,6,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,14.0,6
7,7,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,1.0,0.0,0.0,0,0,0,1.0,14.0,7
8,8,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,4,0.0,0.0,0.0,0,0,0,0.0,12.0,8
9,9,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,16.0,9
10,10,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,19.0,10
11,11,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,1,0.0,0.0,0.0,0,0,0,0.0,17.0,11
12,12,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,0,0.0,0.0,0.0,0,0,0,0.0,5.0,12
13,13,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,1,0.0,0.0,0.0,0,0,0,0.0,9.0,13
14,14,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,1.0,0.0,0.0,0,0,0,1.0,9.0,14
15,15,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,0,0.0,0.0,0.0,0,0,0,0.0,3.0,15
16,16,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,3,0.0,0.0,0.0,0,0,0,0.0,9.0,16
17,17,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,1,0.0,0.0,0.0,0,0,0,0.0,15.0,17
18,18,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,3,0.0,0.0,0.0,0,0,0,0.0,17.0,18
19,19,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,0,0.0,0.0,0.0,0,0,0,0.0,12.0,19
20,20,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,16.0,20
21,21,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,0,0.0,0.0,0.0,0,0,0,0.0,9.0,21
22,22,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,2,0.0,0.0,0.0,0,0,0,0.0,21.0,22
23,23,Merseyside,E08000011,Knowsley,910004,352100,398200,53.478334,-2.723204,U,...,1,0.0,0.0,0.0,0,0,0,0.0,17.0,23
30996,30996,Merseyside,E08000011,Knowsley,967034,347360,392080,53.422877,-2.793591,U,...,11,1.0,0.0,0.0,0,0,0,1.0,55.0,12
30997,30997,Merseyside,E08000011,Knowsley,967034,347360,392080,53.422877,-2.793591,U,...,4,2.0,0.0,0.0,0,0,0,2.0,105.0,13
30998,30998,Merseyside,E08000011,Knowsley,967034,347360,392080,53.422877,-2.793591,U,...,6,2.0,0.0,0.0,0,0,0,2.0,80.0,14
30999,30999,Merseyside,E08000011,Knowsley,967034,347360,392080,53.422877,-2.793591,U,...,2,0.0,0.0,0.0,0,0,0,0.0,44.0,15
31000,31000,Merseyside,E08000011,Knowsley,967034,347360,392080,53.422877,-2.793591,U,...,7,1.0,0.0,0.0,0,0,0,1.0,47.0,16
31001,31001,Merseyside,E08000011,Knowsley,967034,347360,392080,53.422877,-2.793591,U,...,4,1.0,0.0,0.0,0,0,0,1.0,39.0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670310,1670310,Merseyside,E08000011,Knowsley,943047,343455,399391,53.488179,-2.853663,U,...,3,2.0,0.0,0.0,0,0,0,2.0,14.0,6
1670311,1670311,Merseyside,E08000011,Knowsley,943047,343455,399391,53.488179,-2.853663,U,...,5,1.0,0.0,0.0,1,0,0,2.0,17.0,7
1670312,1670312,Merseyside,E08000011,Knowsley,943047,343455,399391,53.488179,-2.853663,U,...,5,0.0,0.0,0.0,0,1,0,1.0,10.0,8
1670313,1670313,Merseyside,E08000011,Knowsley,943047,343455,399391,53.488179,-2.853663,U,...,4,0.0,0.0,0.0,0,3,0,3.0,15.0,9
1670314,1670314,Merseyside,E08000011,Knowsley,943047,343455,399391,53.488179,-2.853663,U,...,3,0.0,0.0,0.0,0,0,0,0.0,35.0,10
1670315,1670315,Merseyside,E08000011,Knowsley,943047,343455,399391,53.488179,-2.853663,U,...,4,0.0,0.0,0.0,0,0,0,0.0,6.0,11
1670316,1670316,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,19,1.0,3.0,0.0,0,1,1,6.0,86.0,12
1670317,1670317,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,35,4.0,0.0,3.0,1,1,5,14.0,157.0,13
1670318,1670318,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,10,1.0,4.0,2.0,0,0,4,11.0,87.0,14
1670319,1670319,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,25,6.0,1.0,1.0,0,4,8,20.0,101.0,15
1670320,1670320,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,25,9.0,2.0,1.0,0,4,4,20.0,92.0,16
1670321,1670321,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,24,8.0,5.0,1.0,0,2,3,19.0,129.0,17
1670322,1670322,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,13,12.0,1.0,3.0,0,1,4,21.0,89.0,18
1670323,1670323,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,29,10.0,2.0,3.0,0,4,8,27.0,127.0,19
1670324,1670324,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,28,4.0,1.0,5.0,0,3,5,18.0,98.0,20
1670325,1670325,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,53,3.0,0.0,4.0,0,2,2,11.0,182.0,21
1670326,1670326,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,25,2.0,0.0,0.0,0,2,3,7.0,154.0,22
1670327,1670327,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,6,0.0,0.0,0.0,0,0,0,0.0,55.0,23
1670328,1670328,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,17,2.0,0.0,0.0,0,0,0,2.0,59.0,0
1670329,1670329,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,18,2.0,0.0,1.0,0,0,0,3.0,65.0,1
1670330,1670330,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,10,1.0,0.0,0.0,0,0,0,1.0,31.0,2
1670331,1670331,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,4,4.0,1.0,1.0,0,1,0,7.0,31.0,3
1670332,1670332,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,15,7.0,1.0,0.0,0,0,0,8.0,50.0,4
1670333,1670333,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,16,2.0,1.0,0.0,0,0,0,3.0,49.0,5
1670334,1670334,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,3,5.0,0.0,0.0,0,0,0,5.0,19.0,6
1670335,1670335,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,15,3.0,1.0,1.0,0,2,0,7.0,45.0,7
1670336,1670336,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,6,2.0,0.0,1.0,0,0,3,6.0,21.0,8
1670337,1670337,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,11,2.0,0.0,1.0,0,0,0,3.0,34.0,9
1670338,1670338,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,4,1.0,0.0,0.0,0,1,0,2.0,26.0,10
1670339,1670339,Merseyside,E08000011,Knowsley,943048,343637,399486,53.489052,-2.850938,U,...,1,0.0,0.0,0.0,0,0,0,0.0,7.0,11

In [57]:
av_df1 = t[t.hours == 1]
av_df1[['Area','Year','dCount','CAR','BUS', 'LGV','HGVR2','HGVR3','HGVR4','HGVA3','HGVA5','HGVA6','HGV','AMV','hours']]

,Area,Year,dCount,CAR,BUS,LGV,HGVR2,HGVR3,HGVR4,HGVA3,HGVA5,HGVA6,HGV,AMV,hours
1,Knowsley,2000,2000-06-08,9,0.0,2,0.0,0.0,0.0,0,0,0,0.0,11.0,1
31009,Knowsley,2000,2000-06-28,36,2.0,3,2.0,0.0,0.0,0,0,0,2.0,43.0,1
38377,Knowsley,2000,2000-03-20,90,3.0,23,5.0,0.0,0.0,0,0,0,5.0,121.0,1
43993,Knowsley,2000,2000-03-27,190,1.0,80,36.0,8.0,5.0,9,18,10,86.0,357.0,1
47857,Knowsley,2000,2000-05-25,18,0.0,3,0.0,0.0,0.0,0,0,0,0.0,21.0,1
52873,Knowsley,2001,2001-06-07,15,0.0,1,0.0,0.0,0.0,0,0,0,0.0,16.0,1
65905,Knowsley,2001,2001-05-04,87,0.0,5,0.0,0.0,0.0,0,1,0,1.0,93.0,1
83785,Knowsley,2001,2001-06-27,34,1.0,3,0.0,0.0,0.0,0,0,0,0.0,38.0,1
91057,Knowsley,2001,2001-03-19,80,4.0,22,1.0,0.0,0.0,0,0,0,1.0,109.0,1
98473,Knowsley,2001,2001-03-26,249,1.0,105,51.0,3.0,3.0,5,17,13,92.0,449.0,1
102337,Knowsley,2001,2001-05-24,42,1.0,5,2.0,0.0,0.0,0,0,0,2.0,50.0,1
107233,Knowsley,2002,2002-05-30,10,1.0,0,0.0,0.0,0.0,0,0,0,0.0,11.0,1
120217,Knowsley,2002,2002-05-03,88,0.0,13,0.0,0.0,0.0,0,0,0,0.0,103.0,1
138073,Knowsley,2002,2002-06-26,40,1.0,2,0.0,0.0,0.0,0,0,0,0.0,43.0,1
145609,Knowsley,2002,2002-03-18,81,4.0,12,2.0,0.0,1.0,0,1,0,4.0,101.0,1
153025,Knowsley,2002,2002-04-08,243,1.0,66,36.0,1.0,6.0,11,21,12,87.0,398.0,1
153361,Knowsley,2002,2002-06-19,318,2.0,30,2.0,3.0,1.0,0,0,0,6.0,357.0,1
153385,Knowsley,2002,2002-05-31,97,5.0,21,3.0,1.0,0.0,0,0,0,4.0,128.0,1
153409,Knowsley,2002,2002-09-25,259,15.0,38,4.0,0.0,1.0,1,1,0,7.0,323.0,1
158377,Knowsley,2002,2002-05-23,27,0.0,3,0.0,0.0,0.0,0,0,0,0.0,30.0,1
163249,Knowsley,2003,2003-06-05,16,0.0,3,0.0,1.0,0.0,0,0,0,1.0,20.0,1
180097,Knowsley,2003,2003-06-04,225,15.0,29,7.0,1.0,1.0,0,0,0,9.0,279.0,1
180121,Knowsley,2003,2003-05-16,329,13.0,24,5.0,0.0,0.0,0,0,0,5.0,371.0,1
180145,Knowsley,2003,2003-06-13,201,6.0,28,7.0,1.0,0.0,0,1,0,9.0,245.0,1
180169,Knowsley,2003,2003-10-10,157,14.0,19,1.0,0.0,0.0,0,0,0,1.0,192.0,1
221113,Knowsley,2003,2003-05-02,76,0.0,12,1.0,0.0,0.0,0,0,0,1.0,90.0,1
238873,Knowsley,2003,2003-06-25,48,2.0,2,0.0,0.0,0.0,0,0,0,0.0,54.0,1
246289,Knowsley,2003,2003-03-17,63,7.0,7,2.0,0.0,0.0,0,0,0,2.0,79.0,1
253705,Knowsley,2003,2003-03-24,212,3.0,66,36.0,7.0,6.0,7,21,11,88.0,370.0,1
254041,Knowsley,2003,2003-06-18,386,6.0,44,5.0,2.0,1.0,0,0,0,8.0,445.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465609,Knowsley,2014,2014-06-03,5,0.0,2,0.0,0.0,0.0,0,0,0,0.0,7.0,1
1465633,Knowsley,2014,2014-09-25,29,0.0,14,1.0,0.0,0.0,0,0,0,1.0,44.0,1
1568569,Knowsley,2015,2015-04-28,46,1.0,28,2.0,0.0,0.0,0,0,0,2.0,77.0,1
1568593,Knowsley,2015,2015-04-28,210,0.0,19,2.0,0.0,0.0,0,0,0,2.0,231.0,1
1568617,Knowsley,2015,2015-03-17,155,7.0,19,0.0,0.0,0.0,0,0,0,0.0,181.0,1
1568641,Knowsley,2015,2015-06-30,486,5.0,55,2.0,0.0,1.0,3,1,0,7.0,554.0,1
1568665,Knowsley,2015,2015-09-18,28,0.0,2,0.0,0.0,0.0,0,0,0,0.0,30.0,1
1568689,Knowsley,2015,2015-10-22,31,0.0,3,0.0,0.0,0.0,0,0,0,0.0,34.0,1
1568713,Knowsley,2015,2015-06-29,12,0.0,2,1.0,0.0,0.0,0,0,0,1.0,15.0,1
1568737,Knowsley,2015,2015-05-06,8,0.0,0,0.0,0.0,0.0,0,0,0,0.0,8.0,1
1568761,Knowsley,2015,2015-10-21,55,1.0,9,0.0,0.0,0.0,0,0,0,0.0,65.0,1
1568785,Knowsley,2015,2015-10-05,25,0.0,1,0.0,0.0,0.0,0,0,0,0.0,26.0,1
1568809,Knowsley,2015,2015-03-24,14,0.0,3,1.0,0.0,0.0,0,0,0,1.0,18.0,1
1568833,Knowsley,2015,2015-03-26,47,0.0,0,2.0,0.0,0.0,0,0,0,2.0,49.0,1
1568857,Knowsley,2015,2015-06-02,13,7.0,8,0.0,2.0,1.0,0,0,1,4.0,32.0,1
1568881,Knowsley,2015,2015-10-01,86,8.0,23,5.0,2.0,5.0,1,0,1,14.0,131.0,1
1670017,Knowsley,2016,2016-04-26,135,1.0,13,0.0,2.0,0.0,0,0,0,2.0,152.0,1
1670041,Knowsley,2016,2016-04-26,226,3.0,20,1.0,1.0,1.0,0,0,0,3.0,252.0,1
1670065,Knowsley,2016,2016-03-15,211,4.0,14,0.0,0.0,0.0,0,0,0,0.0,229.0,1
1670089,Knowsley,2016,2016-06-28,326,4.0,47,3.0,0.0,1.0,0,2,0,6.0,385.0,1
1670113,Knowsley,2016,2016-09-16,17,0.0,6,0.0,0.0,0.0,0,0,0,0.0,23.0,1
1670137,Knowsley,2016,2016-10-20,39,5.0,3,0.0,1.0,1.0,0,0,0,2.0,49.0,1
1670161,Knowsley,2016,2016-06-27,35,0.0,3,0.0,0.0,0.0,0,0,0,0.0,38.0,1
1670185,Knowsley,2016,2016-05-04,9,0.0,5,1.0,0.0,0.0,0,0,0,1.0,15.0,1
1670209,Knowsley,2016,2016-10-19,74,0.0,11,1.0,0.0,0.0,0,0,0,1.0,86.0,1
1670233,Knowsley,2016,2016-10-03,19,0.0,0,0.0,0.0,0.0,0,0,0,0.0,19.0,1
1670257,Knowsley,2016,2016-03-22,13,0.0,4,0.0,0.0,0.0,0,0,0,0.0,17.0,1
1670281,Knowsley,2016,2016-03-24,31,0.0,8,0.0,0.0,0.0,0,0,0,0.0,39.0,1
1670305,Knowsley,2016,2016-05-24,7,0.0,8,0.0,0.0,0.0,0,0,0,0.0,16.0,1
1670329,Knowsley,2016,2016-09-29,44,0.0,18,2.0,0.0,1.0,0,0,0,3.0,65.0,1

In [58]:
av_car_num = av_df1['CAR'].mean()
av_bus_num = av_df1['BUS'].mean()
av_lgv_num = av_df1['LGV'].mean()
av_h2_num = av_df1['HGVR2'].mean()
av_h3_num = av_df1['HGVR3'].mean()
av_h4_num = av_df1['HGVR4'].mean()
av_v3_num = av_df1['HGVA3'].mean()
av_v5_num = av_df1['HGVA5'].mean()
av_v6_num = av_df1['HGVA6'].mean()
av_hgv_num = av_df1['HGV'].mean()
av_amv_num = av_df1['AMV'].mean()

av_veh_sum = (av_car_num + av_bus_num + av_lgv_num + av_h2_num + av_h3_num + av_h4_num + av_v3_num + av_v5_num + av_v6_num + av_hgv_num + av_amv_num)//11

av_veh_sum

30.0